services:
  postgres:
    image: postgres:15-alpine
    container_name: coffee-house-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abdelilah -d blogdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffee-house-backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SECURITY_JWT_SECRET_KEY: ${SECURITY_JWT_SECRET_KEY}
      MEDIA_UPLOAD_DIR: /app/uploads/
      SECURITY_JWT_EXPIRATION_TIME: 3600000
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - coffee-network
      - shared-proxy
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coffee-house-frontend
    environment:
      API_URL: /api
    networks:
      - coffee-network
      - shared-proxy
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  coffee-network:
    driver: bridge
  shared-proxy:
    external: true

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local
